spring.application.name=sentence-ordering-app

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/sentence_app}
spring.datasource.username=${DATABASE_USERNAME:sentence_user}
spring.datasource.password=${DATABASE_PASSWORD:sentence_password}

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:validate}
spring.jpa.open-in-view=false
spring.jpa.show-sql=${SHOW_SQL:false}

server.port=${PORT:8081}
server.forward-headers-strategy=framework
